### ISSUE TITLE
Release libsysstat as version 1 and drop the qt5 suffix

### ISSUE THREAD

**Issue by agaida** [lxde/libsysstat#4]
same reasons as for other libs - if we consider not to have a qt5 suffix we should be strict with it - but this would break razorqt in debian. Set the version to 1 would prevent this.

**Comment by jleclanche** [comment]
closing, we don't care anymore

**Comment by agaida** [comment]
not good - this will conflict with libsysstat provided with razorqt - and razorqt is still and will be in debian for a certain amount of time - you know, its in stable. That means - no new libsysstat in debian, that means: no lxqt-panel in debian - bad luck. We should talk about it again.

**Comment by jleclanche** [comment]
@agaida See https://github.com/lxde/lxqt/issues/704 - we're most likely going to drop libsysstat altogether.

**Comment by agaida** [comment]
agreed - that would be the best solution
